const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const { transformSync } = require("@babel/core");
const store = require("./recordStore.cjs");
const code = transformSync(fs.readFileSync(`${__dirname}/api.js`, "utf8"), {
    configFile: false, babelrc: false, plugins: [require("@babel/plugin-transform-modules-commonjs")],
}).code;
const activity = require("./apiActivity.cjs");
let fetchImpl;
let tokenLookup = async () => null;
const exportsApi = {};
vm.runInNewContext(code, { exports: exportsApi, process: { env: {} }, fetch: (...args) => fetchImpl(...args),
    require: (name) => {
        if (name === "react-native") return { Platform: { OS: "web" } };
        if (name === "./recordStore.cjs") return store;
        if (name === "./apiActivity.cjs") return activity;
        if (name === "./storageAdapter") return { storage: { getItem: () => tokenLookup(), setItem: async () => {}, removeItem: async () => {} } };
        if (["@react-native-async-storage/async-storage", "expo-secure-store"].includes(name)) return {};
        throw new Error(`Unexpected import ${name}`);
    },
});
const api = exportsApi.api;
const response = (data, status = 200) => ({ ok: status < 400, status, text: async () => JSON.stringify(data) });
const tick = () => new Promise(setImmediate);
const ids = (child = 1) => store.getRows(child, "growth").map((r) => r.id).sort((a, b) => a - b);
function seed(child, resource, rows) { store.acceptFetch(child, resource, rows, store.version(child, resource)); }
async function check() {
    store.reset(); seed(1, "growth", [{ id: 1 }, { id: 2 }, { id: 3 }]);
    const stale = store.version(1, "growth");
    const resolves = [];
    fetchImpl = () => new Promise((resolve) => resolves.push(resolve));
    const first = api.optimisticRecord(1, "growth", "delete", 1, {});
    const second = api.optimisticRecord(1, "growth", "delete", 2, {}).catch((e) => e);
    assert.deepEqual(ids(), [3], "Rows disappear synchronously");
    assert.equal(activity.getActiveRequestCount(), 0, "Approved actions never block the app");
    assert.throws(() => api.optimisticRecord(1, "growth", "delete", 1, {}), /awaiting/);
    await tick(); resolves[0](response(null, 204)); await first;
    resolves[1](response({ error: "Rejected" }, 400)); assert.equal((await second).status, 400);
    assert.deepEqual(ids(), [2, 3], "Rollback restores only the failed record");
    store.acceptFetch(1, "growth", [{ id: 1 }, { id: 2 }], stale);
    assert.deepEqual(ids(), [2, 3], "Pre-mutation reads cannot resurrect deleted records");
    seed(2, "growth", [{ id: 9 }]); assert.deepEqual(ids(2), [9]);
    fetchImpl = async () => { throw new Error("Disconnected"); };
    await assert.rejects(api.optimisticRecord(1, "growth", "delete", 2, {}));
    assert.deepEqual(ids(), [3]);
    let op = store.getOperations().find((o) => o.id === 2);
    assert.equal(op.status, "uncertain", "Interrupted writes cannot be called failures");
    fetchImpl = async () => response({ error: "Record not found" }, 404);
    assert.equal(await api.checkMutation(op), true); assert.deepEqual(ids(), [3]);
    assert.throws(() => api.optimisticRecord(1, "vaccinations", "update", 1, {}), /confirmation/);
    assert.throws(() => api.optimisticRecord(1, "nutrition", "create", null, {}), /confirmation/);

    seed(1, "milestones", []);
    fetchImpl = async () => { throw new Error("Lost response"); };
    await assert.rejects(api.optimisticRecord(1, "milestones", "create", null, { title: "Walking", is_completed: true }, { entity: "walking" }));
    op = store.getOperations().find((o) => o.resource === "milestones");
    assert.equal(store.getRows(1, "milestones")[0]._pending, true);
    seed(1, "milestones", [{ id: 40, title: "Walking", is_completed: true, _operation_key: op.key }]);
    assert.equal(store.getRows(1, "milestones").length, 1, "Receipt metadata reconciles a lost create response without a duplicate temporary row");
    assert.equal(store.getRows(1, "milestones")[0].id, 40);

    const attempt = { current: null }, calls = [];
    fetchImpl = async (url, opts) => { calls.push({ url, ...opts }); throw new Error("Lost response"); };
    const failedSave = api.saveRecord(1, "nutrition", null, { quantity: 10 }, attempt);
    assert.equal(activity.getActiveRequestCount(), 1, "Form saves remain blocking");
    await assert.rejects(failedSave);
    const key = calls[0].headers["X-Operation-Key"];
    fetchImpl = async (url, opts) => { calls.push({ url, ...opts }); return response({ id: 50, ...JSON.parse(opts.body) }); };
    await api.saveRecord(1, "nutrition", null, { quantity: 20 }, attempt);
    assert.equal(calls[1].headers["X-Operation-Key"], key);
    assert.equal(JSON.parse(calls[1].body).quantity, 10, "Replay the original payload before accepting changed form fields");
    assert.equal(calls[2].method, "PUT"); assert(calls[2].url.endsWith("/50"));
    await api.saveRecord(1, "nutrition", null, { quantity: 30 }, attempt);
    assert.equal(calls[3].method, "PUT", "Partial-save retries retain the saved record ID");

    seed(1, "growth", [{ id: 7 }]);
    let resolveLate;
    fetchImpl = () => new Promise((resolve) => { resolveLate = resolve; });
    const late = api.optimisticRecord(1, "growth", "delete", 7, {}).catch((e) => e);
    await tick(); store.reset(); seed(1, "growth", [{ id: 7 }]);
    resolveLate(response(null, 204)); await late;
    assert.deepEqual(ids(), [7], "A previous account's late response cannot touch the new session");
    seed(1, "medication-doses", [{ id: 1, medication_id: 2 }, { id: 2, medication_id: 3 }]);
    store.removeMedicationDoses(1, 2);
    assert.deepEqual(store.getRows(1, "medication-doses").map((r) => r.id), [2]);
    assert.equal(activity.getActiveRequestCount(), 0);
    seed(1, "growth", [{ id: 8, date_recorded: "2026-09-18" }]);
    store.confirm(1, "growth", { id: 9, date_recorded: "2026-09-01" });
    assert.equal(store.getRows(1, "growth")[0].id, 8, "Backdated form saves must not become the latest measurement");
    let resolveToken;
    tokenLookup = () => new Promise((resolve) => { resolveToken = resolve; });
    const oldToken = exportsApi.getToken();
    await exportsApi.setToken("new-session-token");
    resolveToken("old-session-token");
    await assert.rejects(oldToken, /Session changed/);
    assert.equal(await exportsApi.getToken(), "new-session-token", "A late credential read cannot overwrite the new session");

    store.reset();
    const empty = store.getSnapshot(1, "shares");
    assert.equal(empty.hasFetched, false);
    assert.equal(store.getSnapshot(1, "shares"), empty, "External-store snapshots are stable between changes");
    fetchImpl = async () => response([]);
    await api.listShares(1, { loading: "nonblocking" });
    assert.equal(store.getSnapshot(1, "shares").hasFetched, true, "Confirmed empty results are known data");
    assert(store.getSnapshot(1, "shares").fetchedAt > 0);
    const knownEmpty = store.getSnapshot(1, "shares");
    fetchImpl = async () => { throw new Error("Offline"); };
    await assert.rejects(api.listShares(1, { loading: "nonblocking" }));
    assert.equal(store.getSnapshot(1, "shares"), knownEmpty, "Failed refreshes preserve rows and freshness metadata");
    fetchImpl = async () => response({ unexpected: "shape" });
    await assert.rejects(api.listShares(1, { loading: "nonblocking" }), /load records/);
    assert.equal(store.getSnapshot(1, "shares"), knownEmpty, "Malformed responses cannot masquerade as empty lists");
    api.seedAccount({ id: "parent", email: "old@example.test" });
    assert.equal(store.getRows(exportsApi.ACCOUNT_SCOPE, exportsApi.ACCOUNT_RESOURCE)[0].email, "old@example.test");
    const pendingReads = [];
    fetchImpl = () => new Promise((resolve) => pendingReads.push(resolve));
    const oldAccount = api.me({ loading: "nonblocking" });
    await tick();
    fetchImpl = async () => response({ user: { id: "parent", email: "new@example.test", city: "Manila" } });
    const updating = api.updateMe({ city: "Manila" });
    assert.equal(activity.getActiveRequestCount(), 1, "Profile saves still block");
    await updating;
    pendingReads.shift()(response({ user: { id: "parent", email: "old@example.test" } }));
    assert.equal((await oldAccount).user.email, "new@example.test", "Older reads cannot overwrite a confirmed profile save");
    fetchImpl = async () => response({ user: { id: "parent", email: "changed@example.test" } });
    await api.changeEmail({});
    assert.equal(store.getRows(exportsApi.ACCOUNT_SCOPE, exportsApi.ACCOUNT_RESOURCE)[0].email, "changed@example.test");

    seed(1, "shares", [{ id: 20, status: "active", generate_date: "2026-09-18" }]);
    fetchImpl = () => new Promise((resolve) => pendingReads.push(resolve));
    const oldShares = api.listShares(1, { loading: "nonblocking" });
    await tick();
    fetchImpl = async () => response({ id: 20, status: "revoked", generate_date: "2026-09-18" });
    const revoking = api.revokeShare(1, 20);
    assert.equal(activity.getActiveRequestCount(), 1, "Revocation still blocks");
    assert.equal(store.getRows(1, "shares")[0].status, "active", "Revocation is not optimistic");
    await revoking;
    pendingReads.shift()(response([{ id: 20, status: "active" }])); await oldShares;
    assert.equal(store.getRows(1, "shares")[0].status, "revoked", "Older refreshes cannot resurrect revoked shares");
    fetchImpl = async () => response({ id: 21, status: "active", generate_date: "2026-09-19" });
    await api.createShare(1, {});
    assert.equal(store.getRows(1, "shares")[0].id, 21, "Confirmed shares are sorted by generation date");
    const newerRead = store.startFetch(1, "access-log"), latestRead = store.startFetch(1, "access-log");
    store.acceptFetch(1, "access-log", [{ id: 2 }], newerRead);
    assert.equal(store.getSnapshot(1, "access-log").hasFetched, false, "Obsolete overlapping reads are ignored");
    store.acceptFetch(1, "access-log", [{ id: 3 }], latestRead);
    assert.equal(store.getRows(1, "access-log")[0].id, 3);
    assert.equal(store.getSnapshot(2, "shares").hasFetched, false, "Child caches are independent");
    fetchImpl = () => new Promise((resolve) => pendingReads.push(resolve));
    const oldSession = api.accessLog(1, { loading: "nonblocking" });
    await tick(); await exportsApi.clearToken();
    pendingReads.shift()(response([{ id: 99 }])); await assert.rejects(oldSession, /Session changed/);
    assert.equal(store.getSnapshot(1, "shares").hasFetched, false);
    assert.equal(store.getRows(exportsApi.ACCOUNT_SCOPE, exportsApi.ACCOUNT_RESOURCE).length, 0, "Logout clears account data too");
    assert.equal(activity.getActiveRequestCount(), 0);
    console.log("Optimistic checks passed: per-record rollback, session isolation, stale reads, receipt reconciliation, blocking forms and safe retries.");
}
check().catch((error) => { console.error(error); process.exitCode = 1; });
