const mem={};
const mock={ getItem:k=>k in mem?mem[k]:null, setItem:(k,v)=>{mem[k]=String(v)}, removeItem:k=>{delete mem[k]} };
global.localStorage=mock; global.window={ localStorage:mock };
const S=require("./shareStore.js");
(async()=>{
  let pass=0,fail=0; const A=(c,m)=>{ c?(pass++,console.log("PASS",m)):(fail++,console.log("FAIL",m)); };
  const share=await S.createShare({childId:"1",childName:"Maya",recordKeys:["profile","vaccinations"],payload:{profile:{name:"Maya"},vaccinations:[{vaccineName:"HepB"}]},ttlMinutes:60});
  A(share.code&&share.code.length>=8,"createShare returns code "+share.code);
  A(share.status==="active","new share active");
  const r1=await S.resolveByCode(share.code);
  A(r1.status==="ok"&&r1.share.payload.profile.name==="Maya","resolveByCode ok returns payload");
  A(S.codeFromQrPayload(S.qrPayloadForCode(share.code))===share.code,"QR payload round-trips to code");
  await S.logAccess({code:share.code,shareId:share.id,childName:"Maya",professionalName:"Dr. Chen",action:"Viewed shared records"});
  const log=await S.logForChild("Maya");
  A(log.length===1&&log[0].professionalName==="Dr. Chen","access log records the view");
  await S.revokeShare(share.id);
  A((await S.resolveByCode(share.code)).status==="revoked","revoked share no longer resolves");
  const exp=await S.createShare({childId:"1",childName:"Maya",recordKeys:["profile"],payload:{},ttlMinutes:-1});
  A((await S.resolveByCode(exp.code)).status==="expired","expired share does not resolve");
  A((await S.resolveByCode("ZZZZ-9999")).status==="notfound","unknown code -> notfound");
  console.log("\nRESULT "+pass+" passed, "+fail+" failed"); process.exit(fail?1:0);
})();
